version: '3.0'
services:
  redis:
    image: redis:5
    container_name: redisdb
    ports:
      - 6379:6379
  postgres:
    image: postgres:12
    container_name: postgresdb
    environment:
      POSTGRES_DB: xe
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgresProvision:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
